In [4]:
import numpy as np
import gym
import random

In [6]:
env = gym.make("FrozenLake-v1")

In [7]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [8]:
action_size

4

In [9]:
state_size

16

In [10]:
def initialize_q_table(nos_space, noa_space): 
    q_table = np.zeros((nos_space, noa_space))
    return q_table

In [12]:
initialize_q_table(state_size, action_size).shape

(16, 4)

In [14]:
qtable = np.zeros((state_size, action_size))
qtable.shape

(16, 4)

In [19]:
def check_2d(observation): 
    if np.array(observation, dtype="object").shape == (2,):
        return True 
    else: return False

In [15]:
total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005   

In [20]:

# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        if check_2d(state): 
            state = state[0]
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info,_ = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.4802
[[1.09167327e-01 7.57908560e-02 9.84214935e-02 4.94509095e-02]
 [3.29756889e-03 2.70878206e-03 1.97307768e-03 9.32563520e-02]
 [1.61110884e-02 5.06584727e-02 1.17783884e-02 7.65328794e-02]
 [1.57842475e-04 4.20966557e-03 9.95684479e-04 3.58964791e-02]
 [1.14556300e-01 3.85317278e-02 8.61715719e-02 8.99074845e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.25181751e-02 5.52063504e-08 2.74774497e-04 2.90560827e-10]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.76240075e-03 4.74948277e-03 2.35782768e-02 9.40463652e-02]
 [4.06575540e-02 6.96025534e-01 4.53093449e-02 1.89012293e-02]
 [5.33862447e-01 8.31630074e-03 2.46669365e-02 3.60731004e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.80566755e-02 2.91077075e-02 4.29880911e-01 6.45357373e-02]
 [3.67114593e-01 8.90565227e-01 2.40581535e-01 8.06120498e-02]
 [0.00000000e+00 0.00000000e+00